# Phần 1: Dùng để đọc/ghi dữ liệu vào Google Sheet
[gcp_service_account]
type = "service_account"
project_id = "ke-gio-giang-day-2025"
private_key_id = "5c0410cd2eb783b27e6fcbe3adcaea3170909555"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDIqfBTkD5ruejv\nRlXVyiNPOaUS7VxgKbD02UtZshlPoFe1YrxnzaZAQKNmZ5FigeM67fASjPfY2Dxb\nFkCccGU4Vd4WF0salTlhYwtB1onAHXMT3Vk7H8z8881r/HHKEH50oOAV+uHld/Hl\n4Kf6rNAhgAKkWft131ZeDMvwiPYKqckpAqZtNO5dslB9j4bygJV8I8e3jgNkUf8x\nKl6d9Y520Iaf/jPTfvBK1x5hsdGee4Rglsm8ntvfQIIGVy/s+YopDeGmti6OaZce\n5p74rLTg193MnnmM1yc/wJj0EIcrhpcNV14rPbkWoy+L1697nGmX6NshtfTv9lj6\n4ySx5RIxAgMBAAECggEAIQpSRwAeNxCyeQuEwKH69GWSd65bon3a5EYPMSKxJjpJ\nltU+Hn1vHW9HOGpfNvAaIS7ic7uAZ9UbAwiD9P5QvFjvK4YEWMkvXIi5ZsrTfa2b\nsC6nLaQL1a6zKU+00MesermujA/2OBlq3CYEorLnxkxUowkp7Xurteq3fdCfapvF\nMgPqw+MV7y4kJ9p89kLnQ/eDG0KksMYZwLJm9Z4ebvRwCyEFMujaRrB2wOss3Q6L\n7J0pAeSNFqnENooEIepTvNEESIJB4TgPI2ob0gN5l8UEeITIf6KD4XjLZJkVnK5G\nlNahcwnDP6bqcGEO/jbf+puwMLnZ2rbv/AywpgqkLQKBgQD8LxW8bWUDqrIwvl9e\nrLl6vLfQ8YXTxi8qIt6PhmSxOZFstqlOktF1FSABiJY0qClXbrnoG9go6qT2vqBJ\nL1QGX7VUcy3rtTEyhMsQbUxcu5Jwlg6eOOIBN5IvSn2kTxXHcUYwASRvHFY4T8rA\nJBGQ/HCsenY7erj+4gYMtRfWCwKBgQDLs0Y25EXTojnoC1M/q3vFG+zBx91Xs1N6\nAoyhL8kilMoGonHCW2ms2aaRIafrPoB15AGdQXc50YATQX5UIaFM3P6pNMzubdlr\nYCtHp+KMTsXWCNEqxJipiA77ezTvrWZRqLTptNQg1NZetZkJdHz2myUtt+DLBg18\nMCTjWfsKMwKBgQDpy2UlWW3q5ldopTWZehxC066+gQuG+BdFwyn+eaPkQfC2jumL\ntMWG/Fy9zzkh/DzHmBm2PAo8dL0XHEdRUhVeC2D6uAV8nnDL2xy/T/UZi7QJuLQ4\nr5endTOLsE2nBMK2MifV3Vk/wU+VyTO4yjeW6NI0tRvjrLTRaA4fvcwpXQKBgGhZ\nxX13QUIiV/HEY3g5e+VE4et/XKeBySC2z53/IdWiTUBK1WYQeDlBInA0wpXjZeF+\n1Uje8Znf9fFnWrT0qXH7wEWkM9ts0LWOBX3mxkrES9rSl3yGTAKFHc+8lSi3NrRc\nbZlPtl+/SLYp52UNlLqsTcZ27SR0TFIzQ6JoRQ87AoGAIIeEC6aL10pj+1Lcn8rc\nMDbh9vBvWtuMjZCUomFWoOl0CHBDe+qX+rBbFbh/gPtBifc8z6xpMGWniJpj4Q7R\n6rQHXZJKmmzN+EjdNyAh1dc1u4krD+PjCYsQRoNayxFIAwEyWH7rSK6xkScOCEgU\n1Kdj05XJGWfUyGxizynF+s4=\n-----END PRIVATE KEY-----\n"
client_email = "kegio-sheets@ke-gio-giang-day-2025.iam.gserviceaccount.com"
client_id = "104592172560118895127"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/kegio-sheets%40ke-gio-giang-day-2025.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

# Phần 2: Dùng cho chức năng đăng nhập
[google_oauth]
clientId = "1079846301695-lddu5u594f2cht65j4c4d3th0e4vu86d.apps.googleusercontent.com"
clientSecret = "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"
redirectUri = "http://localhost:8501/"
redirectUri = "https://ke-khai-gio-day-nam2025.streamlit.app/"
# URL này phải khớp với URL bạn đã cấu hình trên Google Cloud

# Phần 3: Cấu hình tên file và trang tính
[google_sheet]
sheet_name = "email_user"
sheet_name_id = "11NdJwRDAh6fLjP7k6SjnysOUya_6IXP2tGTEAyd_tQw"
user_mapping_worksheet = "User_Mapping" # email và magv
target_folder_name = "KE_GIO_2025"
template_file_id = "191Su3TKN3BQwQIVh6pzV-kiy3jKivHsd59kueaU-0Tw"

# Cấu hình tên file và trang tính
admin_data_folder_name = "DỮ_LIỆU_QUẢN_TRỊ"
admin_data_sheet_name = "DATA_KEGIO"

[admin_email]
address = "admin@cdktdaklak.edu.vn"
app_password = "ftvp xjzt naph mxze"


